spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/backend?createDatabaseIfNotExist=true
    username: root
    password: toor
  jpa:
    show-sql: true
  jwt:
    signingKey: ${JWT_SIGNING_KEY}
    registerRequestTokenExpiration: 600 # = 60 * 10 = 10 Minuten
    accessTokenExpiration: 300 # = 60 * 5 = 5 Minuten
    refreshTokenExpiration: 604800 # = 60 * 60 * 24 * 7 = 7 Tage
