### Registrieren
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "email": "admin.one@bibliobytes.at",
  "firstName": "admin",
  "lastName": "one",
  "password": "123456"
}

### Code bestätigen:
POST http://localhost:8080/users/register/confirm
Cookie: register_token={{registerToken}}
Content-Type: application/json

{
  "code": {{code}}
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin.one@bibliobytes.at",
  "password": "123456"
}

### Alle Nutzer anzeigen
GET http://localhost:8080/users
Authorization: Bearer {{accessToken}}

### Alle "APPLICANTS" anzeigen
GET http://localhost:8080/users/applicants
Authorization: Bearer {{accessToken}}

### Rolle vergeben:
PUT http://localhost:8080/users/updateRole
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "685ff23f-05df-47d1-aa8c-e00143f5c4ef",
  "role": "USER"
}

### Eigenen Vorname ändern
### Eigenen Nachnamen ändern
### Eigene Email ändern
### Eigenes Passwort ändern

### Fremden Vorname ändern
PUT http://localhost:8080/users/updateProfile
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "685ff23f-05df-47d1-aa8c-e00143f5c4ef",
  "firstName": "user"
}

### Fremden Nachname ändern
PUT http://localhost:8080/users/updateProfile
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "685ff23f-05df-47d1-aa8c-e00143f5c4ef",
  "lastName": "one"
}

### Fremde Email ändern
PUT http://localhost:8080/users/updateCredentials
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "685ff23f-05df-47d1-aa8c-e00143f5c4ef",
  "newEmail": "user.one@bibliobytes.at"
}

### Fremdes Passwort ändern
PUT http://localhost:8080/users/updateCredentials
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "685ff23f-05df-47d1-aa8c-e00143f5c4ef",
  "newPassword": "123456"
}